### ISSUE TITLE
Compilation dies at 100%

### ISSUE THREAD

**Issue by lachlansimpson** [luntergroup/octopus#40]
Took me a while to get it working, but eventually got this to compile on CentOS 7.5:

`export HTSLIB_ROOT=/config/binaries/htslib/1.9; ./scripts/install.py --prefix=/config/binaries/octopus/0.5.2 -c /config/binaries/gcc/8.2/bin/gcc -cxx /config/binaries/gcc/8.2/bin/g++ --clean --boost /config/binaries/boost/1.68.0/ `

```
[100%] Linking CXX executable octopus
/tmp/ccJ9HFwD.ltrans2.ltrans.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std:
:__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<ch
ar> > const&, int) [clone .constprop.1896]':
<artificial>:(.text+0x15d3e): undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_err
or::kind_t)'
<artificial>:(.text+0x15d52): undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, 
std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::b
asic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/tmp/ccJ9HFwD.ltrans2.ltrans.o:(.rodata+0x540): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::
basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccJ9HFwD.ltrans2.ltrans.o:(.rodata+0xbc0): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::
basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccJ9HFwD.ltrans2.ltrans.o:(.rodata+0x1618): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11:
:basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccJ9HFwD.ltrans2.ltrans.o:(.rodata+0x2918): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11:
:basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccJ9HFwD.ltrans3.ltrans.o: In function `void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<cha
r> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_strin
g<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int) [clone .constprop.1659]':
<artificial>:(.text+0xd8e6): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_trai
ts<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::bas
ic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/tmp/ccJ9HFwD.ltrans3.ltrans.o: In function `void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<cha
r> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_strin
g<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int) [clone .constprop.1659] [clone .cold.12]':
<artificial>:(.text.unlikely+0x306): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<cha
r, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans3.ltrans.o: In function `void boost::program_options::validate<int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::c
har_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, lon
g) [clone .constprop.1656] [clone .cold.21]':
<artificial>:(.text.unlikely+0x77f): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<cha
r, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans3.ltrans.o: In function `void boost::program_options::validate<octopus::MemoryFootprint, char>(boost::any&, std::vector<std::__cxx11::basi
c_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > 
> > const&, octopus::MemoryFootprint*, long) [clone .constprop.1631] [clone .cold.22]':
<artificial>:(.text.unlikely+0x878): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<cha
r, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans3.ltrans.o: In function `void boost::program_options::validate<float, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std:
:char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, float*,
 long) [clone .constprop.1625] [clone .cold.23]':
<artificial>:(.text.unlikely+0x999): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<cha
r, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans3.ltrans.o: In function `void boost::program_options::validate<boost::filesystem::path, char>(boost::any&, std::vector<std::__cxx11::basic
_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >
 > const&, boost::filesystem::path*, long) [clone .constprop.1621] [clone .cold.24]':
<artificial>:(.text.unlikely+0xa92): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<cha
r, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans3.ltrans.o:<artificial>:(.text.unlikely+0xc38): more undefined references to `boost::program_options::invalid_option_value::invalid_option
_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
/tmp/ccJ9HFwD.ltrans3.ltrans.o:(.rodata+0x70c10): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std:
:vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char
>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans3.ltrans.o:(.rodata+0x70ca8): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std:
:vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char
>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans3.ltrans.o:(.rodata+0x70d40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std:
:vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char
>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans3.ltrans.o:(.rodata+0x70dd8): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std:
:vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char
>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans3.ltrans.o:(.rodata+0x70e70): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std:
:vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char
>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans3.ltrans.o:(.rodata+0x70f08): more undefined references to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&
, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_trait
s<char>, std::allocator<char> > > > const&, bool) const' follow
/tmp/ccJ9HFwD.ltrans29.ltrans.o: In function `void boost::log::v2_mt_posix::type_dispatcher::callback_base::trampoline<boost::log::v2_mt_posix::binder1st<boos
t::log::v2_mt_posix::output_fun, boost::log::v2_mt_posix::expressions::aux::stream_ref<boost::log::v2_mt_posix::basic_formatting_ostream<char, std::char_trait
s<char>, std::allocator<char> > >&>, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >(void*, std::__cxx11::basic_str
ing<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)':
<artificial>:(.text+0x3046): undefined reference to `boost::log::v2_mt_posix::aux::code_convert_impl(wchar_t const*, unsigned long, std::__cxx11::basic_string
<char, std::char_traits<char>, std::allocator<char> >&, unsigned long, std::locale const&)'
<artificial>:(.text+0x3085): undefined reference to `boost::log::v2_mt_posix::aux::code_convert_impl(wchar_t const*, unsigned long, std::__cxx11::basic_string
<char, std::char_traits<char>, std::allocator<char> >&, unsigned long, std::locale const&)'
<artificial>:(.text+0x3154): undefined reference to `boost::log::v2_mt_posix::aux::code_convert_impl(wchar_t const*, unsigned long, std::__cxx11::basic_string
<char, std::char_traits<char>, std::allocator<char> >&, unsigned long, std::locale const&)'
/tmp/ccJ9HFwD.ltrans29.ltrans.o: In function `boost::recursive_mutex::recursive_mutex()':
<artificial>:(.text+0x1462a): undefined reference to `boost::system::detail::generic_category_instance'
<artificial>:(.text+0x1467a): undefined reference to `boost::system::detail::generic_category_instance'
<artificial>:(.text+0x146cb): undefined reference to `boost::system::detail::generic_category_instance'
/tmp/ccJ9HFwD.ltrans29.ltrans.o: In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::text_file_backend>::try_consume
(boost::log::v2_mt_posix::record_view const&)':
<artificial>:(.text+0x21009): undefined reference to `boost::log::v2_mt_posix::sinks::text_file_backend::consume(boost::log::v2_mt_posix::record_view const&, 
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans29.ltrans.o: In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::text_file_backend>::consume(boo
st::log::v2_mt_posix::record_view const&)':
<artificial>:(.text+0x21221): undefined reference to `boost::log::v2_mt_posix::sinks::text_file_backend::consume(boost::log::v2_mt_posix::record_view const&, 
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans30.ltrans.o: In function `boost::program_options::typed_value<boost::filesystem::path, char>::name[abi:cxx11]() const':
<artificial>:(.text+0x172ea): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans30.ltrans.o: In function `boost::program_options::typed_value<bool, char>::name[abi:cxx11]() const':
<artificial>:(.text+0x1756a): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans30.ltrans.o: In function `boost::program_options::typed_value<int, char>::name[abi:cxx11]() const':
<artificial>:(.text+0x177ea): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans30.ltrans.o: In function `boost::program_options::typed_value<octopus::MemoryFootprint, char>::name[abi:cxx11]() const':
<artificial>:(.text+0x17a6a): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans30.ltrans.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name() const':
<artificial>:(.text+0x17cea): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans30.ltrans.o:<artificial>:(.text+0x17f6a): more undefined references to `boost::program_options::arg[abi:cxx11]' follow
/tmp/ccJ9HFwD.ltrans30.ltrans.o: In function `boost::program_options::typed_value<bool, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
<artificial>:(.text+0x57c9): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool*, int)'
/tmp/ccJ9HFwD.ltrans30.ltrans.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
<artificial>:(.text+0x58e9): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/tmp/ccJ9HFwD.ltrans30.ltrans.o: In function `boost::program_options::typed_value<double, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const [clone .cold.66]':
<artificial>:(.text.unlikely+0xf8d): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans30.ltrans.o: In function `boost::program_options::typed_value<std::vector<int, std::allocator<int> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const [clone .cold.79]':
<artificial>:(.text.unlikely+0x18ff): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans30.ltrans.o:(.rodata+0xea8): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccJ9HFwD.ltrans30.ltrans.o:(.rodata+0xf40): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::system::error_category::std_category::equivalent(std::error_code const&, int) const':
<artificial>:(.text+0xc47e): undefined reference to `boost::system::detail::generic_category_instance'
<artificial>:(.text+0xc4c5): undefined reference to `boost::system::detail::generic_category_instance'
<artificial>:(.text+0xc505): undefined reference to `boost::system::detail::generic_category_instance'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const':
<artificial>:(.text+0xc54d): undefined reference to `boost::system::detail::generic_category_instance'
<artificial>:(.text+0xc595): undefined reference to `boost::system::detail::generic_category_instance'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
<artificial>:(.text+0x12c8d): undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
<artificial>:(.text+0x12cd0): undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `octopus::options::conflicting_options(boost::program_options::variables_map const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
<artificial>:(.text+0x13614): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
<artificial>:(.text+0x13645): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::program_options::typed_value<std::vector<int, std::allocator<int> >, char>::name[abi:cxx11]() const':
<artificial>:(.text+0x14a1a): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::program_options::typed_value<octopus::options::ExtensionLevel, char>::name[abi:cxx11]() const':
<artificial>:(.text+0x14c9a): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::program_options::typed_value<std::vector<octopus::options::ContigPloidy, std::allocator<octopus::options::ContigPloidy> >, char>::name[abi:cxx11]() const':
<artificial>:(.text+0x14f1a): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::program_options::typed_value<octopus::options::RefCallType, char>::name[abi:cxx11]() const':
<artificial>:(.text+0x1519a): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::program_options::typed_value<float, char>::name[abi:cxx11]() const':
<artificial>:(.text+0x1541a): undefined reference to `boost::program_options::arg[abi:cxx11]'
/tmp/ccJ9HFwD.ltrans31.ltrans.o:<artificial>:(.text+0x1569a): more undefined references to `boost::program_options::arg[abi:cxx11]' follow
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char> >::try_consume(boost::log::v2_mt_posix::record_view const&)':
<artificial>:(.text+0x19139): undefined reference to `boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char>::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char> >::consume(boost::log::v2_mt_posix::record_view const&)':
<artificial>:(.text+0x19351): undefined reference to `boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char>::consume(boost::log::v2_mt_posix::record_view const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `octopus::options::run(boost::program_options::basic_command_line_parser<char>&) [clone .cold.74]':
<artificial>:(.text.unlikely+0x19c5): undefined reference to `boost::program_options::error_with_option_name::get_canonical_option_name[abi:cxx11]() const'
<artificial>:(.text.unlikely+0x1a52): undefined reference to `boost::program_options::error_with_option_name::get_canonical_option_name[abi:cxx11]() const'
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `octopus::options::parse_config_file(boost::filesystem::path const&, boost::program_options::variables_map&, boost::program_options::options_description const&) [clone .cold.76]':
<artificial>:(.text.unlikely+0x2462): undefined reference to `boost::program_options::error_with_option_name::get_canonical_option_name[abi:cxx11]() const'
/tmp/ccJ9HFwD.ltrans31.ltrans.o:(.rodata+0x2240): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans31.ltrans.o:(.rodata+0x22d8): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans31.ltrans.o:(.rodata+0x2370): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans31.ltrans.o:(.rodata+0x2408): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans31.ltrans.o:(.rodata+0x24a0): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/tmp/ccJ9HFwD.ltrans31.ltrans.o:(.rodata+0x2538): more undefined references to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const' follow
/tmp/ccJ9HFwD.ltrans31.ltrans.o: In function `main':
<artificial>:(.text.startup+0x1db): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
<artificial>:(.text.startup+0x383): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
<artificial>:(.text.startup+0x5c1): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
<artificial>:(.text.startup+0xb17): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
<artificial>:(.text.startup+0xd16): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/tmp/ccJ9HFwD.ltrans31.ltrans.o:<artificial>:(.text.startup+0x119c): more undefined references to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/octopus] Error 1
make[1]: *** [src/CMakeFiles/octopus.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by datakid** [comment]
Am just trying a boost re-installation now.

**Comment by dancooke** [comment]
Did you have any joy with this? As discussed in another issue (#43), I've tried to improve the installation script so that all dependencies can be installed locally. You should now just be able to use:

```shell
$ git clone https://github.com/luntergroup/octopus.git
$ octopus/scripts/install.py --install-dependencies
```

to install Octopus from scratch (cmake, GCC, Boost, and htslib are all installed to `octopus/build` using Homebrew).

**Comment by datakid** [comment]
I've moved on from that organisation. I've left details of where I was up to, but I don't know that this will ever be answered - sorry!
