### ISSUE TITLE
Installation script is not using the version of git or curl on the path

### ISSUE THREAD

**Issue by TBradley27** [luntergroup/octopus#160]
Hey, 

Thanks for writing what looks to be a very promising tool. I have one or two problems trying to install the latest version however:

**Describe the bug**
The installation script attempts to use git and curl installed in /usr/bin/ rather than the version of git and curl on the path

**Version**: Version 0.7.2

```shell
$ octopus --version
// PASTE OUTPUT HERE
```

**Command**
Command line to install octopus:
```shell
$ octopus/script/install.py --dependencies
```

![image](https://user-images.githubusercontent.com/13511784/113683187-d1edb780-96bb-11eb-8c15-1bb0d05fa65f.png)

**Comment by TBradley27** [comment]
A quick side-note to this:

I was able to successfully (I think) compile the tool by not using the '--dependency' flag at at all - and instead opting to install required dependencies via conda. This is all done within a separate conda environment.

The only slight problem is that even at version 7.x.x of gcc my compilation failed, but worked with version 9.3.0 of gcc

I am running a quick job now, but the tool looks to have been compiled successfully using this approach

**Comment by dancooke** [comment]
Hey, the automatic dependency install option is currently not working on CentOS 7 due to a [problem with Homebrew](https://github.com/Homebrew/linuxbrew-core/issues/22511). I was hoping this would be fixed by now but it's taken a while so I may look at other options soon. Your workaround using Conda should be fine - it's what I'm doing. Indeed, GCC7 doesn't work due to various compiler bugs.
